services:
  task_db:
    image: 'postgres:latest'
    container_name: task_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskdb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: task_app
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task_db:5432/taskdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: 'true'
    depends_on:
      - task_db
  test:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: task_tests
    command: ./mvnw test
    depends_on:
      - task_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task_db:5432/taskdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
volumes:
  postgres_data: